### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by RiteshSec** [N0rz3/GitSint#2]
- I can successfully run GitSint using Python 3.11.9 for an Email. 
- But when I use it with a valid Username I get the following error. 
![image](https://github.com/N0rz3/GitSint/assets/110530131/cbc87827-2e27-4cad-b471-44662d70d0f4)

Can anyone help in resolving this?

**Comment by N0rz3** [comment]
Hi, your problem is due to your version of GitSint `2.2.1` because the tool is now in `2.2.6` so you just have to reinstall the tool.

**Comment by RiteshSec** [comment]
Hi @N0rz3, 

- Thank you for the quick response. I have deleted the existing version in my system and installed the 2.2.6 version but I still get the same error. However, I can run the tool for an email. ![image](https://github.com/N0rz3/GitSint/assets/110530131/d7a7b87c-90f5-4988-b6b1-fb62797dc4ae)

----
- Also, I have observed that for a given email we are only getting the username. The target profile is public and has not enabled the options you mentioned under the "Protection" section in the documentation to stay safe. Is this expected? since the documentation showed that the tool will provide a lot more information than just the username.

**Comment by N0rz3** [comment]
Hi so for the error with GitLab I'm thinking of removing this functionality because Gitlab changes its tags all the time it seems because this is not the first time this has happened. And for email then the tool only gives the username but it doesn't matter you can simply re-execute with the use `-u` with the nickname found.
